from cassandra.cluster import Cluster
from cassandra.auth import PlainTextAuthProvider
import json


def get_cluster():
    # This secure connect bundle is autogenerated when you download your SCB, 
    # if yours is different update the file name below
    cloud_config= {
    'secure_connect_bundle': 'secure-connect-fastapi-db.zip'
    }

    # This token JSON file is autogenerated when you download your token, 
    # if yours is different update the file name below
    with open("ibeawuchiclaret@gmail.com-token.json") as f:
        secrets = json.load(f)

    CLIENT_ID = secrets["clientId"]
    CLIENT_SECRET = secrets["secret"]

    auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
    cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider)
    return cluster

def get_session():
    cluster = get_cluster()
    session = cluster.connect()

    row = session.execute("select release_version from system.local").one()
    if row:
        print(row[0])
    else:
        print("An error occurred.")
    return session
